services:
  zns:
    image: blackmini/zns
    container_name: zns
    ports:
      - "37443:37443"
      - "37443:37443/udp"
    volumes:
      - ./certs:/app/certs
      - ./web:/app/web
      - /root/certs/_.microsoft.com.crt:/app/certs/fullchain.pem 
      - /root/certs/_.microsoft.com.key:/app/certs/privkey.pem 
    environment:
      - ZNS_UPSTREAM
      - ZNS_DB
      - ZNS_PRICE
      - ZNS_FREE
