name: Docker构建和发布

on:
  push:
    branches: [ "no-ecs" ]
  pull_request:
    branches: [ "no-ecs" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: 输出调试信息
        run: |
          echo "GitHub SHA: ${{ github.sha }}"
          echo "DOCKERHUB_USERNAME 是否设置: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "DOCKERHUB_TOKEN 是否设置: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
          go version
          go env

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/zns:${{ github.sha }}

      - name: 输出构建结果
        run: echo "Docker镜像构建并推送完成"